services:
  db:
    image: postgres:14-alpine
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "6432:5432"   # внешний порт 6432, как в обсуждении
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
